tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface": "#faf9f9",
        "inverse-on-surface": "#f2f0f0",
        "inverse-surface": "#2f3031",
        "inverse-primary": "#b4c5ff",
        "surface-tint": "#0052dd",
        "tertiary-fixed-dim": "#ffb59d",
        "on-error-container": "#93000a",
        "secondary-fixed": "#e5e2e1",
        "on-primary": "#ffffff",
        "on-secondary-container": "#636262",
        "primary": "#004ccd",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "tertiary": "#9e3100",
        "surface-container-highest": "#e3e2e2",
        "on-background": "#1b1c1c",
        "surface-container-high": "#e9e8e8",
        "on-primary-fixed": "#00174c",
        "on-tertiary": "#ffffff",
        "outline": "#737687",
        "surface-dim": "#dbdad9",
        "error": "#ba1a1a",
        "outline-variant": "#c3c6d8",
        "on-surface": "#1b1c1c",
        "on-tertiary-fixed-variant": "#832700",
        "surface-container": "#efeded",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#390c00",
        "secondary-fixed-dim": "#c8c6c5",
        "on-error": "#ffffff",
        "on-primary-container": "#f3f3ff",
        "on-primary-fixed-variant": "#003da9",
        "tertiary-fixed": "#ffdbd0",
        "secondary-container": "#e2dfde",
        "on-tertiary-container": "#fff1ed",
        "surface-container-low": "#f4f3f3",
        "primary-fixed": "#dbe1ff",
        "primary-container": "#0f62fe",
        "secondary": "#5f5e5e",
        "on-surface-variant": "#424656",
        "tertiary-container": "#c84000",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e2e2",
        "surface-bright": "#faf9f9",
        "error-container": "#ffdad6",
        "background": "#faf9f9"
      },
      "borderRadius": {
        "DEFAULT": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      "spacing": {
        "space-xl": "2rem",
        "space-md": "1rem",
        "margin-sm": "1rem",
        "gutter": "1rem",
        "gutter-compact": "0.5rem",
        "space-xs": "0.25rem",
        "margin": "1.5rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem"
      },
      "fontFamily": {
        "body-sm": ["IBM Plex Sans"],
        "label-md": ["IBM Plex Sans"],
        "headline-md": ["IBM Plex Sans"],
        "label-sm": ["IBM Plex Sans"],
        "headline-lg": ["IBM Plex Sans"],
        "headline-sm": ["IBM Plex Sans"],
        "code-sm": ["Courier Prime", "monospace"],
        "body-md": ["IBM Plex Sans"],
        "body-lg": ["IBM Plex Sans"],
        "code-md": ["Courier Prime", "monospace"],
        "headline-xl": ["IBM Plex Sans"]
      },
      "fontSize": {
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "22px", "fontWeight": "600" }],
        "code-sm": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "code-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-xl": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  }
}
